# Enter your per-environment constants below

development: &default
  shrimp_server: 'http://localhost:4000'

production:
  <<: *default
  shrimp_server: 'http://mantis-shrimp.heroku.com'
  
test:
  <<: *default